### ISSUE TITLE
White cable and board version

### ISSUE THREAD

**Issue by gotros** [bipropellant/bipropellant-hoverboard-firmware#106]
Hi @EmerickH @p-h-a-i-l ,

in the foto of the wiring with the pinout is a white cable, which is not explained - what is it used for?

Are there different board versions that differ other than color of the pcb etc?

Thank you in advance,
gotros

**Comment by EmerickH** [comment]
Hi,
I don't have such cables on my boards but I would say it's a power output for the audio Bluetooth board on some hoverboards.
If you have a theses cables and a multimeter you can test the voltage beetween them, it should be something beetween 12v and 48v (don't remember exactly).

There are 2 main PCB designs, the one on the photo + 2 sensor boards, and a version with only 2 sensors boards that are controlling each one a motor (not supported yet by this project).
On each design they are multiples versions of the boards (usually minor differences: different LEDs/connectors position...), that may be just revisions or different brands, we don't know, but all boards seems to use the same pinout on the GD32/STM32 and should be compatible.
