### ISSUE TITLE
scale used twice in main.c

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/bipropellant-hoverboard-firmware#24]
`int scale[2]` and `float scale` (in PPM code)

**Comment by btsimonh** [comment]
neither are used.
int scale[2] was intended to replace the /3 in
`pwms[i] = CLAMP(dirs[i]*(sensor_data[i].complete.Angle - sensor_data[i].Center)/3+dspeeds[i], -FlashContent.HoverboardPWMLimit, FlashContent.HoverboardPWMLimit);`
giving ability to change the sensitivity to angle. 

It should really be a constant in sensor_data now, and maybe initialised from flash.
as should dirs?

I'll do a quick mod when I get time.

**Comment by btsimonh** [comment]
removed
