### ISSUE TITLE
Missing protocol.h at make

### ISSUE THREAD

**Issue by papaxiclas** [bipropellant/bipropellant-hoverboard-firmware#29]
Hello!
When trying to compile your code I get a "no such file or directory" about the #include "protocol.h" on the main file. Is it really missing from the repo?

Thanks

**Comment by btsimonh** [comment]
have you checked out the subrepo (https://github.com/bipropellant/bipropellant-protocol) too?
if so, you should have a 'hbprotocol' subfolder filled with good stuff in your folder.
If not, not exactly sure how you do it in every different form of git access....

**Comment by papaxiclas** [comment]
Not realized it was a different repo! :D sorry!

**Comment by p-h-a-i-l** [comment]
Clone with submodules: `git clone --recurse-submodules`
Or afterwards:  `git submodule update --init --recursive`
