### ISSUE TITLE
STM32 Utility ST link v2 USB-Dongle is not work

### ISSUE THREAD

**Issue by uhi2000** [bipropellant/bipropellant-hoverboard-firmware#40]
Hello,
I have a problem with flashing the firmware with Windows 10. I have connected the USB -ST link v2 dongle as described without 3.3v. 
The STM32 ST Utility 004 writes "Can not connect to target". I really do not use the 3.3volts?  "why"???
please help....  I really not use the 3.3volts?
I have connected the motherboard with an external power supply 36V.

**Comment by AntumArk** [comment]
Have you powered your board with battery?

**Comment by uhi2000** [comment]
I have an external power supply connected.
I have an external 36v power supply connected.
Can I now connect the 3.3 Volts on hoverboard mainboard ????
without that which goes crash....

**Comment by AntumArk** [comment]
you need to hold power button when flashing. Otherwise, you need to disconnect power supply, and connect stlink with 3.3v. It should flash.

**Comment by uhi2000** [comment]
thanks my friend, I will try it tonight......I hope it works

**Comment by uhi2000** [comment]
if I put the USB-Link dongle in the USB port of my PC, then I press the connected button in the STM32 Link Utility. but it always comes the error message "no target connected" of the stick but recognized in the STM32 link. What do I'm wrong ???
as long as there is no connection with the USB stick, I can not flash!!!please help me...

**Comment by AntumArk** [comment]
Can you send me a photo of your setup? Have you unlocked your hoverboard?

**Comment by uhi2000** [comment]
i am beginner, please tell me where can i upload pictures here?

**Comment by AntumArk** [comment]
https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by uhi2000** [comment]
![20190614_163410](https://user-images.githubusercontent.com/51678077/59523261-1994c500-8ed1-11e9-819d-2709b25b179c.jpg)

**Comment by uhi2000** [comment]
![20190614_163323](https://user-images.githubusercontent.com/51678077/59523284-2a453b00-8ed1-11e9-880f-98b762b81bc5.jpg)

**Comment by uhi2000** [comment]
![20190614_163307](https://user-images.githubusercontent.com/51678077/59523315-40eb9200-8ed1-11e9-9c2e-a46ee7fd9776.jpg)

**Comment by uhi2000** [comment]
the Hoverboard Mainboard is new..

**Comment by uhi2000** [comment]
I wanted to flash it with the Hverboard Hack master

**Comment by AntumArk** [comment]
Connection mode - connect under reset (instead of normal).

Also attach how is your system connected(electronics).

Do you have linux system?

**Comment by uhi2000** [comment]
![st-link_connection (1)](https://user-images.githubusercontent.com/51678077/59523614-0afadd80-8ed2-11e9-8e41-1470416cb1d0.jpg)

**Comment by uhi2000** [comment]
no windows 10

**Comment by uhi2000** [comment]
and so I connected it. as described

**Comment by AntumArk** [comment]
Connect 3.3v from Stlink to hoverboard and try again. Be SURE that your battery is disconnected!

**Comment by uhi2000** [comment]
and put the dongle in  my usb port .This is right..power on and hold button...no akku no power supply on? ???

**Comment by uhi2000** [comment]
no power on???

**Comment by uhi2000** [comment]
ok, I'll try it right away

**Comment by AntumArk** [comment]
Do not connect the battery.

**Comment by uhi2000** [comment]
I just do not understand why Niklas Fauth shows the picture with 3 cables instead of 4 connections. that is not correct

**Comment by AntumArk** [comment]
Because there are two ways of flashing. Flashing with and without battery. 
Flashing without battery is safer. 

Without battery you also connect stlink 3.3v.
With battery you do shouldn't connect 3.3v from stlink.

**Comment by uhi2000** [comment]
I thank you first for your help and will try it out. I hope I get a connection and then can flash

**Comment by AntumArk** [comment]
@btsimonh Do you know how to unlock hoverboard on Windows? I only know how to do it in linux.

**Comment by uhi2000** [comment]
i dont no

**Comment by btsimonh** [comment]
I used OCD on windows too... I think.  Was not easy :(

**Comment by uhi2000** [comment]
I think I have the new board--AT32F403RCT6
![58367409-3d22ac00-7edf-11e9-9aea-a9cae4b0134e](https://user-images.githubusercontent.com/51678077/59532286-91221e80-8ee8-11e9-825b-17b72de3324d.jpg)

**Comment by uhi2000** [comment]
I think that does not work with the Hover.Master Hack.-Hex file..or yet?

**Comment by AntumArk** [comment]
It is different series controller than original hoverboard. This code is for 103 series. Unfortunately you will need to look for another repository for that black board.

And for your green one, you need linux operating system computer (raspberry pi, or dual boot linux) to unlock your board before you can upload code.

**Comment by uhi2000** [comment]
sorry i have the old board stm32f103 .soory but the old mainboard but still no connection

**Comment by uhi2000** [comment]
shit

**Comment by AntumArk** [comment]
Try using openocd on windows, or get linux

**Comment by btsimonh** [comment]
Seems at one time I wrote it up :)
try
https://github.com/btsimonh/hoverboard-firmware-hack/blob/newprotocol/otherboards/YST-6.5-10-PCBA-10/programming.md

**Comment by btsimonh** [comment]
@uhi2000 - I can't quite read the CPU identifier - but it's not an ST chip. no?
Maybe it has different programming needs?
A 'true' ST utility will most likely not connect on commercial grounds :).
But OpenOCD should (and should help you identify the chip, I guess).

when you have it running, pls buzz these:
![image](https://user-images.githubusercontent.com/3137332/59548204-89439800-8f43-11e9-85e1-fc5b21119923.png)
to the CPU to see what extra lines we have :).  Then document in the wiki the board identification and the likely available pins, if you have the time.
Also this:
![image](https://user-images.githubusercontent.com/3137332/59548221-d3c51480-8f43-11e9-8960-8f0eae2aef3b.png)

**Comment by btsimonh** [comment]
found this:
https://www.eevblog.com/forum/microcontrollers/problems-compiling-code-for-at32f403/
does not help a lot, but worth following.

**Comment by uhi2000** [comment]
thanks for help, i have a MainboardSTM32F103RCT6, maybe it's locked

**Comment by uhi2000** [comment]
if I put the USB-Link dongle in the USB port of my PC, then I press the connected button in the STM32 Link Utility. but it always comes the error message "no target connected" of the stick but recognized in the STM32 link. What do I'm wrong ???
as long as there is no connection with the USB stick, I can not flash!!!please help me...i have the 3,3volts connected and the mainboard is blinking and piep, and i hold the power-Button!!!

**Comment by uhi2000** [comment]
![20190615_121810](https://user-images.githubusercontent.com/51678077/59550242-a3dc3800-8f68-11e9-9923-c9a18b764e54.jpg)
![Uploading 20190615_111110.jpg…]()

**Comment by uhi2000** [comment]
![20190615_111110](https://user-images.githubusercontent.com/51678077/59550251-b22a5400-8f68-11e9-8eb5-87f993b8ac47.jpg)

**Comment by uhi2000** [comment]
![ST-LINK^V2](https://user-images.githubusercontent.com/51678077/59550291-27962480-8f69-11e9-9703-6f19bbb26ad8.jpg)
i have order  now!!!

**Comment by AntumArk** [comment]
your wiring is incorrect. 3.3v is correct but others not.

**Comment by uhi2000** [comment]
yes is correct

**Comment by uhi2000** [comment]
the mainboard is blinking

**Comment by uhi2000** [comment]
and piep

**Comment by uhi2000** [comment]
but no connected with STM32 or STM8

**Comment by uhi2000** [comment]
shit

**Comment by uhi2000** [comment]
mybe the USB Dongle is defect??

**Comment by AntumArk** [comment]
Your red(swclk) wire goes to last pin in your photo. Last wire should be SWDIO. 

Your brown wire(swdio) goes to third pin in your photo. It should be  GND.

**Comment by uhi2000** [comment]
![20190615_124028](https://user-images.githubusercontent.com/51678077/59550414-dc7d1100-8f6a-11e9-9543-e1030bef0ccf.jpg)

**Comment by uhi2000** [comment]
white03,3v---GND=Black

**Comment by AntumArk** [comment]
switch black with brown, then red with brown. And then send me a photo.

**Comment by uhi2000** [comment]
i have seen the mistake there are different sicks soory

**Comment by uhi2000** [comment]
sorry

**Comment by uhi2000** [comment]
![20190615_125331](https://user-images.githubusercontent.com/51678077/59550595-ba848e00-8f6c-11e9-8355-e6ebc7bc0c3e.jpg)
![20190615_125347](https://user-images.githubusercontent.com/51678077/59550598-beb0ab80-8f6c-11e9-91c8-73a52aa555b9.jpg)

**Comment by uhi2000** [comment]
Great that was the mistake, but I have a new one
![20190615_130104](https://user-images.githubusercontent.com/51678077/59550700-06840280-8f6e-11e9-910d-daac09160d8f.jpg)

**Comment by uhi2000** [comment]
ok its work thanks for help

**Comment by btsimonh** [comment]
Yeah! let us know how you get on with the firmware :) - and what your project is going to be....

**Comment by uhi2000** [comment]
i use the firmware  hoverboard master hack.

**Comment by uhi2000** [comment]
it is a shool-project.
I would like to connect a ps2 controller or the Wii nunshuk

**Comment by uhi2000** [comment]
Now I have the next problem after flashing the firmware hack master .Hex-file
When I turn on the H.Board it makes a power up routine for about 10sec .after the power is down!! Why???
![20190615_160349](https://user-images.githubusercontent.com/51678077/59553078-10b6f880-8f90-11e9-9c30-6ee3e4cdaa65.jpg)

**Comment by uhi2000** [comment]
![20190615_160332](https://user-images.githubusercontent.com/51678077/59553093-347a3e80-8f90-11e9-937b-1c0ddfb9bee8.jpg)

**Comment by btsimonh** [comment]
@uhi2000 - this repo has not been used for ps2 controller or the Wii nunshuk for some time - it may not work.  You may be better off starting with the [original](https://github.com/NiklasFauth/hoverboard-firmware-hack) repo?

Are you building the repo, or using the .hex file in the build folder?  I cannot confirm operation of the hover.hex file in the repo....  and can't advise ref control from either of the above controllers - simply never done it....

**Comment by uhi2000** [comment]
yeah, everything works now

**Comment by uhi2000** [comment]
![20190615_161008](https://user-images.githubusercontent.com/51678077/59553652-00a31700-8f98-11e9-8f1d-daa2553e3b27.jpg)
this is my project...

**Comment by uhi2000** [comment]
one more question: how can I best reduce the max.speed? and is there a possibility to install an elect.Bremse?

**Comment by btsimonh** [comment]
if you are working with this repo, and you have serial,
then use my new branch mentioned in https://github.com/bipropellant/bipropellant-hoverboard-firmware/pull/39
then use the serial command

`fcl300\n` (for example - to limit current to 3A - fcl accepts current A x 100).

when you have chosen a current limit, use

`fm1234\n`

to set flash....

all done :).

**Comment by uhi2000** [comment]
Sorry, I'm not there yet

**Comment by btsimonh** [comment]
p.s. ref solid attachment to the hoverboard, see wiki/project/btsimonh.  I drilled out some holes and used M6 bolts :).  Not utilised yet, and 3d printed retainer not done completely yet, but seems a good option...

**Comment by uhi2000** [comment]
Sorry, I'm not there yet

**Comment by uhi2000** [comment]
The chair should be for disabled people. It must not be too fast.
safety first

**Comment by uhi2000** [comment]
I'm wondering if I'm using a nunshuk or a joystick

**Comment by AntumArk** [comment]
change 1000 to lower value for both wheels. https://github.com/NiklasFauth/hoverboard-firmware-hack/blob/3e2cfe973a2f8289ad8324f89b414501e96ced17/Src/main.c#L242

**Comment by AntumArk** [comment]
You are using joystick( 2ADC channels)

**Comment by uhi2000** [comment]
is better a hall Joystick???

**Comment by AntumArk** [comment]
@uhi2000 better than what? Nunchuck? - yes, it is more stable.

**Comment by uhi2000** [comment]
just for your info, I'm not a programmer. I'm glad I made it this far

**Comment by uhi2000** [comment]
my english is not so good, i am a german-guy

**Comment by uhi2000** [comment]
what is the best firmware for my project ?

**Comment by uhi2000** [comment]
I would like to thank both of you very much for your help ...

**Comment by btsimonh** [comment]
one thing.
There is a difference between speed and power (drive).
Limiting the current (e.g fcl300) and limiting the drive from your joystick (the 1000 thing) are the same thing...  they both limit power.  This works well if you are on the flat, and don't want to squash someone.

However, it will, not go uphill, even slowly.

So...  for a school project, you have a choice.  Limit power as above, or set speed (learn to program a bit :) ).  The pid controlled speed works, just not from your input device.  You may also wish to limit power with the fcl thing.....

If you use this repo, you WILL need to build it to adjust it to your input method.  I'd also strongly suggest you get serial access.... so no hex file which does what you need at the moment.

**Comment by uhi2000** [comment]
I wanted to do that too. Today is my first step

**Comment by btsimonh** [comment]
for a non programmer, you have done well so far :).
install vscode and platformio, and it installs all the tools you need for you - so most of the pain is avoided.  then it's just a bit of 'C' code  :).  keep at it....

**Comment by uhi2000** [comment]
Thank you, I will give my best .. and I think that you are a good helper .. I just need a little time.

**Comment by uhi2000** [comment]
so i have download now the vscode and install ok

**Comment by uhi2000** [comment]
system or user installer??

**Comment by uhi2000** [comment]
platformio install ok

**Comment by jackcha76** [comment]
Hi.
Open check STM32 Link dongle's case. check pin out position btw board and case.
In my case SWDIO and SWCLK are reverted. 
If you would see the mismatching, They to change pin of SWCLK and SWDIO.
It would work if the dongle is recognized by your Windows, and The device driver was installed properly.
Thankx. JK CHA
