### ISSUE TITLE
Motor Current type in BLDC.c

### ISSUE THREAD

**Issue by atc1441** [bipropellant/bipropellant-hoverboard-firmware#45]
Hi, in line 259 in file BLDC.c is a type, the accerage current will always be for the Left motor even when you try to read motor[1]

>   electrical_measurements.motors[0].dcAmpsAvgAcc += ABS(adc_buffer.dcl - offsetdcl);
>   electrical_measurements.motors[1].dcAmpsAvgAcc += ABS(adc_buffer.dcl - offsetdcl);

see here: https://github.com/bipropellant/bipropellant-hoverboard-firmware/blob/9b913c315debcded13eda893997dcdcc1ef07425/src/bldc.c#L258

**Comment by btsimonh** [comment]
yep, noticed that and fixed in the sinsquash PR.

**Comment by atc1441** [comment]
Ok than you know it :) i will close the issue.
Have a great week.
