### ISSUE TITLE
Update protocol submodule to master branch from #p27

### ISSUE THREAD

**Issue by AntumArk** [bipropellant/bipropellant-hoverboard-firmware#47]
@btsimonh Are you working to update protocol submodule? I am just trying to remind you in case you may forget.

**Comment by btsimonh** [comment]
I think it's done (it was a few mins after the main repo....)?  pls confirm it all builds once both masters are pulled....

**Comment by AntumArk** [comment]
![image](https://user-images.githubusercontent.com/23199497/60161941-284c7780-9801-11e9-83b7-909e3bbea452.png)
It is still detached head. 

Building things now :D

**Comment by btsimonh** [comment]
subrepos - bahh...  trying to fix it now!

**Comment by btsimonh** [comment]
pls check again.  all should be good now.

**Comment by AntumArk** [comment]
@btsimonh Everything built successfully.

**Comment by AntumArk** [comment]
Ok, now it is latest commit, but still detached head. 
![image](https://user-images.githubusercontent.com/23199497/60162767-ddcbfa80-9802-11e9-82ea-d916fd69352d.png)
You can't make PR to detached heads.

**Comment by btsimonh** [comment]
hmm...   not seeing that through github or sourcetree....
Are you working from btsimonh or bipropellant?  - they should be the same, but the btsimonh one is a little of a plaything.

**Comment by AntumArk** [comment]
bipropellant 

Cloning with reccursive submodules using gitbash, then adding all repos to github desktop.

**Comment by btsimonh** [comment]
ok, I'll try a small mod on each and commit from github, change to readme maybe.  one moment.

**Comment by AntumArk** [comment]
In the meantime I am trying to clone on Sourcetree

**Comment by AntumArk** [comment]
Same thing, it checks out on that specific commit. 
![image](https://user-images.githubusercontent.com/23199497/60163874-31d7de80-9805-11e9-84d2-e2862c0308ed.png)
Although it can handle submodules, where github desktop - not.

**Comment by p-h-a-i-l** [comment]
Well, detached head is "ok" when working with submodule. A submodule does not reference a branch or head, it references a single commit. This way you can make sure that the "main" repo decides which commit is ok.

You can open git in your submodule folder and checkout the correct branch. This way the head shouldnt be detached anymore.

**Comment by AntumArk** [comment]
@btsimonh It is now synced. Head is now synced upon cloning. 
![image](https://user-images.githubusercontent.com/23199497/60165366-d4915c80-9807-11e9-9fa4-e558be7f5c74.png)

**Comment by EmanuelFeru** [comment]
@btsimonh, maybe you can update the Travis link in Readme to point to the bipropellant build check. At the moment it links to my fork Travis build.

**Comment by p-h-a-i-l** [comment]
> @btsimonh, maybe you can update the Travis link in Readme to point to the bipropellant build check. At the moment it links to my fork Travis build.

done

**Comment by btsimonh** [comment]
> In the meantime I am trying to clone on Sourcetree

I use sourcetree for all my windows git operations; it's not perfect for submodules, but I'm kind of getting used to it :).

**Comment by p-h-a-i-l** [comment]
I gave up on using a fancy GUI for git. Just using the built in functions from vscode and git bash.
