### ISSUE TITLE
Unwanted PowerOn problem

### ISSUE THREAD

**Issue by AntumArk** [bipropellant/bipropellant-hoverboard-firmware#64]
I have this odd problem, when board powers on as soon as the battery is connected. You could expect this if the power button is faulty, but no! It reacts to button presses and turns off to endless bleep. Tried with original firmware and got same result. 
Do you have any idea what went wrong?

**Comment by p-h-a-i-l** [comment]
one of the TIP127 is damaged

**Comment by AntumArk** [comment]
> one of the TIP127 is damaged

Ok, I will check it out.

**Comment by p-h-a-i-l** [comment]
![2019-07-08 13_09_29-Clipboard](https://user-images.githubusercontent.com/10248772/60805888-c3d6d400-a181-11e9-95f8-35e1e0e16a9b.png)
This one probably.

**Comment by AntumArk** [comment]
To what level resistance should vary compared to healthy one?

**Comment by AntumArk** [comment]
I got 450 and 770 on outer legs. While new ones has 956.

**Comment by p-h-a-i-l** [comment]
I'd check with diode mode, not resistance

**Comment by AntumArk** [comment]
They seem to be fine. No shorts.

**Comment by p-h-a-i-l** [comment]
Weird. Thats's exactly the behaviour I see when that part is damaged. Replaced quiete a few already..
Did you check the middle leg in diode mode?

**Comment by AntumArk** [comment]
Yes, both are fine. Replacing them to check if they were bad quality

**Comment by AntumArk** [comment]
Yep. Replaced both of them and now it works. So changed resistance is also a sign of burned or damaged tip127. I suggest to add this to documentation.

**Comment by p-h-a-i-l** [comment]
> Yep. Replaced both of them and now it works. So changed resistance is also a sign of burned or damaged tip127. I suggest to add this to documentation.

Great, please do!

**Comment by btsimonh** [comment]
I didn't think there was a restriction :). - i'm fine with every contribution...

**Comment by AntumArk** [comment]
In progress.

**Comment by AntumArk** [comment]
How do you add photo from google photos? It cant seem to load

**Comment by btsimonh** [comment]
what id do is:

**Comment by AntumArk** [comment]
https://github.com/bipropellant/bipropellant-hoverboard-firmware/wiki/Hardware-troubleshooting Check it out

**Comment by p-h-a-i-l** [comment]
Looking good, thanks!

**Comment by sjamthe** [comment]
This is not directly related but may be you can help.
I am using usart2 to drive my hoverboard
As soon as usart us connected it powers on without me pressing power button.
When the timeout kickin it powers off and on again.

How do I change this behavior? I can't see in code what signals power on on
usart ?

**Comment by AntumArk** [comment]
What do you mean by connected? physically or opened a port?

**Comment by btsimonh** [comment]
Maybe you are (by mistake) supplying power down the red wire?  I'd imagine if you feed 5v down the red wire, the board MCU would power up (because you're feeding enough to the input of the 12v->3.3v).  Once the board powers up, it would then feed 12v back at you, possibly smoking the device feeding the power!.  (but an interesting idea for anyone who wants 'wake on lan' functions! - feed it from a diode & control the voltage fed....).

**Comment by sjamthe** [comment]
Just checked my connections.
1. I am not supplying power from UART. Have only connected GND, TX, RX
2. I AM connected to the battery power,
3. As soon as I connect the USB-Serial cable to my raspberry pi and if
raspberry pi is powered on the hoverboard wakes up with a chime as if I
have pressed the power on button.

So obviously some signal is coming over over RX to signal the
micro-controller to come out of power off mode. I have not tried debugger
so not sure how. Also, I am using code from Tom's branch
<https://github.com/sjamthe/hoverboard-firmware-hack> on AT32 which is
behind all the changes here (like no PID etc.)

**Comment by p-h-a-i-l** [comment]
As this is a separate Issue, I just creatde a new one :)
For future googlers!

**Comment by sjamthe** [comment]
Thanks. I guess probably I don't really understand how the power on / off
works.
I noticed I copied timeout=0 in my settings just as it was in ADC control.

When the power off is called does the mcu go to sleep state ? Then does the
power button pin wakes it up when pressed ?

Is it possible that uart being connected wakes the mcu ? Just a guess.
