### ISSUE TITLE
Repository Name

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/bipropellant-hoverboard-firmware#8]
I noticed today, that our repo name might be quite confusing..

First working Firmware for Hoverboard: [Hoverboard-Board-Hack](https://github.com/salviador/Hoverboard-Board-Hack)
Niklas' refactoring: [hoverboard-firmware-hack](https://github.com/NiklasFauth/hoverboard-firmware-hack)
Isabelle's hard fork: [HoverboardFirmware](https://github.com/isabellesimova/HoverboardFirmware)
Fork for split motor controller [Hoverboard-Firmware-Hack-Gen2](https://github.com/flo199213/Hoverboard-Firmware-Hack-Gen2)

Ours [hoverboard-firmware](https://github.com/bipropellant/hoverboard-firmware)

I think this will lead to a lot of confusion..

**Comment by EmerickH** [comment]
I totally agree, what about renaming to **bipropellant-firmware**?

**Comment by p-h-a-i-l** [comment]
Ilike it, only thing would be that it's harder to find. I think most people search for hoverboard.

**Comment by btsimonh** [comment]
the differentiation here is
1/ ability to use it as a hoverboard (not important to ether of you :) )
2/ the reliable machine protocol.
BOTH are important :)

**Comment by p-h-a-i-l** [comment]
Let's not focus the name too much on our current main features, who knows what will come?

**Comment by lalalandrus** [comment]
Balancing hoverboard firmware

**Comment by btsimonh** [comment]
there are a couple or arduino based projects using normal motors with fairly good explanations and code;  one of my next tasks is to tap a few holes in the top of the HB to facilitate mounting of different 'bodies'.  For balancing, you need some decent mass some distance above the HB.

**Comment by p-h-a-i-l** [comment]
What about simply "bipropellant-hoverboard-firmware"?

**Comment by p-h-a-i-l** [comment]
@btsimonh and @EmerickH: Let's try to make a decision soon, this repo is gaining popularity and it's GPN Next week :)

**Comment by btsimonh** [comment]
"bipropellant-hoverboard-firmware" +1

**Comment by btsimonh** [comment]
renamed :)
