### ISSUE TITLE
Issue building with PlatformIO missing protocol.h

### ISSUE THREAD

**Issue by mrsllez** [bipropellant/bipropellant-hoverboard-firmware#88]
When trying to compile the firmware, I get an error saying I am missing dependency protocol.h. 
![error](https://user-images.githubusercontent.com/58341998/71374002-60b6ed80-25b9-11ea-99ec-845b1bc4e9b3.jpg)

**Comment by p-h-a-i-l** [comment]
Did you checkout everything including submodules? 
See https://github.com/bipropellant/bipropellant-hoverboard-firmware#building-and-flashing

**Comment by mrsllez** [comment]
Thanks..i completely missed that

**Comment by kekersdev** [comment]
Having the same issue despite cloning correctly
`hbprotocol` is present in the `src` folder and it's contents (including `protocol.h`) are recognized by VSC but PIO still with `fatal error: protocol.h: No such file or directory`
