### ISSUE TITLE
Doesn't Connect board to PMM.

### ISSUE THREAD

**Issue by ilkarataev** [bipropellant/bipropellant-hoverboard-firmware#94]
Hi, i want to configure hoverboard working with PPM protocol(speed and steering).I built the project with platformio and only declared PPM section, loaded it to the board and when I connected r6 transmitter (i had one more), connected it to Green right cable UART - nothing moved. I tried so many times with another clone of the project as well. I don't have signal analyzing to see what is happening.
And i don't quite understand the README section about "Sensor data can control the PWM demands (power to the wheels). Double tap on pads to enable." What is "Double tap on pads" - is it "double tap the power button?" I am not very good at English and sorry for this.

I set up platformio.ini only like this: default_envs = control_PPM need i enable define control_PPM and PPM_NUM_CHANNELS 6?

I tried many times but it doesn't work.
I would very appreciate it if you could give some advice.

**Comment by ilkarataev** [comment]
Hi i found the answer, if someone have this issue you need add the same count of channels that your transmitter have.In my case i had RC6 with ten channels and when i add the PPM_NUM_CHANNELS 10 all start work, sorry for my bad english

**Comment by Andrew-rw** [comment]
In my case for FS-IA6B receiver PPM_NUM_CHANNELS=8 worked. 
Helped this issue: https://github.com/NiklasFauth/hoverboard-firmware-hack/issues/158
